### PR TITLE
(FM-5728) Update changelog for 2.1.0

### PR DESCRIPTION
**Pull request by jpogran**
Update changelog and metadata.json for release

### CODE REVIEW

**Comment by ferventcoder** [comment]
Let's move this to 2.1.0? Thoughts @puppetlabs/modules @puppetlabs/windows ?

**Comment by glennsarti** [comment]
I voted for 2.1  @Iristyle for 2.0.4.  Reasoning was, it's not a public or breaking API or ABI change.  It's an implementation detail.

**Comment by ferventcoder** [comment]
PowerShell v2 with .NET 2.0 no longer works with the PowerShell Manager. That's a small but big enough change to probably necessitate the bump.

**Comment by glennsarti** [comment]
Sold.

**Comment by ferventcoder** [comment]
@jpogran 👍  2.1.0?

**Comment by ferventcoder** [comment]
Ping

**Comment by jpogran** [comment]
Updated to 2.1.0

**Comment by Iristyle** [comment]
Already merged, but I'm in agreement with the `2.1.0` versioning given the PS2 / .NET2 behavior change.

**Pull request merged**
