### PR TITLE
(maint) modsync update - master

### PR DESCRIPTION
**Pull request by glennsarti**
The PR contains the updates from the new modsync config for windows;

- LICENSE, NOTICE, CONTRIBUTING, MAINTAINERS updates (where applicable)
- Gemfile, Appveyor, Travis, gitignore cleanup

https://github.com/puppetlabs/modulesync_configs/pull/66
https://github.com/puppetlabs/modulesync_configs/pull/63
https://github.com/puppetlabs/modulesync_configs/pull/62
https://github.com/puppetlabs/modulesync_configs/pull/61

### CODE REVIEW

**Comment by jpogran** [comment]
👍

**Comment by ferventcoder** [comment]
Given most of this is going to merge up from stable, why both ?

**Comment by glennsarti** [comment]
There were a lot of differences between stable and master across the modules.  Given that it's a simple thing to target master, I chose to just take the pain and do each branch on it's own

**Comment by ferventcoder** [comment]
This will need to be rebased after #95

**Comment by glennsarti** [comment]
Rebased

**Pull request merged**
