### PR TITLE
Powershell Facts

### PR DESCRIPTION
**Pull request by cyberious**

### CODE REVIEW

**Comment by tphoney** [comment]
@Iristyle @ferventcoder is this something that needs to be looked at ?

**Comment by ferventcoder** [comment]
@tphoney yes, right now it probably needs a ticket in JIRA though.

**Comment by ferventcoder** [comment]
@cyberious ping - If no further progress is made on this PR within 7 days we will need to close this for now. We value your contributions, but without any forward movement we cannot keep this open.

**Comment by glennsarti** [comment]
No further progress has been made.  Closing this PR.

**Pull request closed without merging**
