### PR TITLE
(maint) modulesync 65530a4 Update Travis

### PR DESCRIPTION
**Pull request by michaeltlombardi**
Related: https://github.com/puppetlabs/modulesync_configs/pull/177

### CODE REVIEW

**Comment by michaeltlombardi** [comment]
Looks like our [`.sync.yml`](https://github.com/puppetlabs/puppetlabs-powershell/blob/master/.sync.yml#L11) is causing the Travis fix not to be picked up.

**Comment by glennsarti** [comment]
```
.travis.yml:
  unmanaged: true
```

**Comment by glennsarti** [comment]
@michaeltlombardi  I have a fix PR for the travis problem but it's dependant on upstream changes first, which will render this PR obsolete (wrong commit hash)

**Comment by glennsarti** [comment]
Is superseded by https://github.com/puppetlabs/puppetlabs-powershell/pull/208

**Pull request closed without merging**
