### PR TITLE
(MODULES-2207) Update Modulesync

### PR DESCRIPTION
**Pull request by ferventcoder**
This ensures the following items are under moduleysnc:

* .gitignore
* .travis.yml
* CONTRIBUTING.md
* Gemfile
* appveyor.yml
* spec/spec.opts

Most importantly, this ensures that acl has up to date Gemfile, Travis CI and
AppVeyor configurations that allow it to be tested properly.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Expected failure on this one.

**Comment by ferventcoder** [comment]
Well that was no fun to fix.

**Comment by ferventcoder** [comment]
w00t! \0/ 

Finally...

**Comment by ferventcoder** [comment]
@cyberious @Iristyle @joshcooper @jpogran this is ready to look at.

**Comment by Iristyle** [comment]
So on 7d13076, we change our testing matrix to `3.4.0` for AppVeyor and TravisCI, but our metadata claims `3.x` compatibility at https://github.com/puppetlabs/puppetlabs-powershell/blob/master/metadata.json#L32

So are we concerned about a testing blind spot for older versions of Puppet?

**Comment by ferventcoder** [comment]
@Iristyle thought we mentioned this elsewhere, but handling the metadata.json updates will be done with a separate ticket (for all repos affected). And IMHO the oldest version blind spot is low risk as compared to not having testing at all. We may decide to move the oldest version to 3.4.0 in the metadata.json updates ticket.

**Comment by cyberious** [comment]
@ferventcoder considering this was not in puppetlabs namespace until 3.4 I would see no reason why 3.4.0 wouldn't be the oldest, also I believe the risk to be minimal between 3.0 and 3.4

**Comment by cyberious** [comment]
:+1:

**Comment by ferventcoder** [comment]
Pushed latest changes. Looks like I was able to back it all the way up to 3.0.0, which is the actual oldest supported.

**Comment by ferventcoder** [comment]
have a bit of a tweak I'll be pushing - once that comes in and goes green I will notify.

**Comment by cyberious** [comment]
gtg

**Pull request merged**
