### PR TITLE
(maint) Add HTML anchor tag

### PR DESCRIPTION
**Pull request by clairecadman**
The anchor tag helps fix broken links — If the header text changes (gets localized) the link will brake.

### CODE REVIEW

**Comment by joshcooper** [comment]
Unfortunately we discovered that anchors don't work, because the forge strips them when rendering the README. Not sure what next steps are @ehom and @scotje?

**Comment by scotje** [comment]
As far as I can tell in my testing, the method utilized here:

https://github.com/puppetlabs/puppetlabs-yumrepo_core/compare/test/master

Seems to work fine in the browsers I tested with.

**Comment by ehom** [comment]
@joshcooper @clairecadman 
we are currently looking into migrating all markdown files to our documentation locaiization platform.

if we take out the HTML anchors, the links to the page anchors will not work since Transifex does not expose the links to the anchors in the localization editor. If we are okay with that, will can remove the HTML anchors.

**Comment by clairecadman** [comment]
@ehom Okay! Should I remove them from all of them or just this one?

**Pull request closed without merging**
